// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"main/common/config"
	"main/meili"
	"main/mgrpc"
	"main/web"
)

// Injectors from wire.go:

// 初始化SSE服务
func InitSSEService(cfg *config.Config) *web.SSERuleService {
	sseRuleService := web.NewWebSSERuleService(cfg)
	return sseRuleService
}

// 初始化SSE服务
func InitGRPCRuleService(cfg *config.Config) *mgrpc.GRPCRuleService {
	grpcRuleServer := mgrpc.NewGRPCRuleService(cfg)
	return grpcRuleServer
}

// 初始化MeiliSearch服务
func InitMeiliService(cfg meili.ClientConfig) *meili.ClientService {
	serviceManager := meili.NewClient(cfg)
	clientService := meili.NewMeiliService(serviceManager)
	return clientService
}
