// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"main/common/config"
	"main/monitor"
	"main/rules/meili"
	"main/rules/mgrpc"
	"main/rules/web"
)

// Injectors from wire.go:

// 初始化SSE服务
func InitSSEService(cfg *config.Config) *web.SSERuleService {
	webConfig := web.NewSSEConfig(cfg)
	sseRuleService := web.NewWebSSERuleService(webConfig)
	return sseRuleService
}

// 初始化GRPC服务
func InitGRPCRuleService(cfg *config.Config) *mgrpc.GRPCRuleService {
	mgrpcConfig := mgrpc.NewGRPCConfig(cfg)
	grpcRuleService := mgrpc.NewGRPCRuleService(mgrpcConfig)
	return grpcRuleService
}

// 初始化MeiliSearch服务
func InitMeiliService(cfg *config.Config) *meili.ClientService {
	meiliConfig := meili.NewMeiliConfig(cfg)
	clientService := meili.NewMeiliService(meiliConfig)
	return clientService
}

// 初始化Monitor服务
func InitMonitorService(cfg *config.Config) *monitor.CanalMonitorService {
	sseRuleService := InitSSEService(cfg)
	grpcRuleService := InitGRPCRuleService(cfg)
	clientService := InitMeiliService(cfg)
	canalMonitorService := monitor.NewMonitorService(cfg, sseRuleService, grpcRuleService, clientService)
	return canalMonitorService
}
