database:
  addr: 192.168.3.158:3307
  user: root
  password: quc@2022@din
  flavor: mysql
  serverId: 1001
  # 禁用 mysqldump
  dumpExecutionPath: ""
  includeTableRegex:
    - "^qucdin_local\\.*"

watchHandlers:
  - table: "qucdin_lcoal\\.business_data.tpl_node_*"
    tableTest: qucdin_lcoal.business_data.tpl_node_v8iuq3pqxl061bd1
    meiliSearchIndex:
      index: "tpl_node"
      # 搜索字段
      searchers:
        - "title"
      # 筛选字段
      filters:
        - "id"
      # 排序字段
      sorts:
        - "created_at"
        - "updated_at"
    rules:
      - grpc
      - sse
      - meili

subscribeServerConfig:
  grpc:
    enable: true
    addr: ":10821"
  sse:
    enable: true
    addr: ":10820"
  meili:
    enable: true
    addr: http://192.168.60.10:7700
    apiKey: root123456