database:
  addr: 192.168.3.158:3307
  user: root
  password: quc@2022@din
  flavor: mysql
  server_id: 1001
  # 禁用 mysqldump
  dump_execution_path: ""
  include_table_regex:
    - "^qucdin_local\\.*"

watch_handlers:
  - table: "qucdin_lcoal\\.business_data_tpl_node_*"
    rules:
      - GRPCRule
      - SSERule
      - MeiliSearchRule
web:
  addr: ":10820"
grpc:
  addr: ":10821"
meili_search:
  addr: "http://192.168.60.10:7700"
  api_key: "root123456"
