database:
  addr: 192.168.3.158:3307
  user: root
  password: quc@2022@din
  flavor: mysql
  server_id: 1001
  # 禁用 mysqldump
  dump_execution_path: ""
  include_table_regex:
    - "^qucdin_local\\.business_data_tpl_node_*"
    - "^qucdin_local\\.business_data_tpl_project_*"

watch_handlers:
  - table: "qucdin_lcoal\\.business_data_tpl_node_*"
    handler: TplNodeHandler

