database:
  addr: 192.168.10.150:3306
  user: root
  password: 123456
  flavor: mysql
  server_id: 1001
  # 禁用 mysqldump
  dump_execution_path: ""
  include_table_regex:
    - "bigdata\\.*"

watch_handlers:
  - table: "bigdata\\.user_info"
    handler: TplNodeHandler

